### PR TITLE
Some new features (Ghost-Deathmatch #209, Verbose HUD #271, and more...)

### PR DESCRIPTION
**Pull request by Bara**
Deadline: *16th Oct. 2018*
--- 

General changes:
---
- CREDITS.md slightly updated (for better overview)

What will be added with this pull request:
---
- [Build] SourceMod 1.10 Builds
- #128 
  - `ttt_disable_rounds` - Default: `0` - `Disable TTT Rounds? This will require an map change, server restart or plugin that can execute TTT_TerminateRound.`
- #180 
  - `revive_traitor_price` - Default: `9000` - `The amount of credits for Revive costs as traitor. 0 to disable.`
  - `revive_detective_price` - Default: `0` - `The amount of credits for Revive costs as detective. 0 to disable.`
  - `revive_traitor_sort_prio` - Default: `0` - `The sorting priority of the Revive (Traitor) in the shop menu.`
  - `revive_detective_sort_prio` - Default: `0` - `The sorting priority of the Revive (Detective) in the shop menu.`
  - `revive_traitor_count` - Default: `1` - `The amount of usages for Revive per round as traitor. 0 to disable.`
  - `revive_detective_count` - Default: `1` - `The amount of usages for Revive per round as detective. 0 to disable.`
  - `revive_time_traitor` - Default: `10` - `Revive time for traitors?`
  - `revive_time_detective` - Default: `10` - `Revive time for detectives?`
  - `revive_time_to_accept` - Default: `10` - `Time in seconds to accept the revive request.`
  - `revive_time_to_next_message` - Default: `1` - `Show just 1 message every x second when you try to revive someone. Why? -> Move during revive and you can spam the chat. 0 - Disabled`
- #209 
  - **_NOT DONE YET_**
- #271 
  - Add convar `hud_display_karma_type` - Default: `1` - `Which karma display you want. 0 - Number (Old), 1 - Name (New)`
  - Add convar `hud_display_health_type` - Default: `1` - `Which health display you want. 0 - Number (Old), 1 - Name (New)`
- #296 
- #357 
  - Add convar `ta_cooldown_after_round_start` - Default: `30.0` - `Disable taser for X seconds after round starts (0.0 to disable it)`
  - Add convar `ta_cooldown_after_round_start_message` - Default: `1` - `Show message when tasers are enabled?`
- #358  
  - Add convar `ta_glow_player_after_taser` - Default: `1` - `Glow player on taser? ( 0 - Disable, 1 - Enable)` 
  - Add convar `ta_glow_player_length` - Default: `5` - `How long should the player glow?, Time in Seconds, 0 - Disabled` 
  - Add convar `ta_glow_player_for_all` - Default: `1` - `Glow player for all (ta_broadcast_taser_result must be 1 for this)? ( 0 - Disable, 1 - Enable)`
- #359 
- #360
  - Add convar `ttt_shop_show_credits_as_money` - Default: `1` - `Show player credits as csgo money?`
- Other fixed issues: #364  #365 #366 #368 
- [Core Command] `sm_version` - Shows the version of TTT
- [Core Command] `sm_respawn <#userid/name>` - Respawn one or more players
  - ConVar: `ttt_respawn_admin_access` - Default: b - `Admin flags to access respawn command.` 
- [Core Config] `ttt_players_remaining_hud_message` - Default: 1 - `Show hud \"We Are / Players Remaining\" message during non active rounds?`
- [Core Stock] `TTT_ShowProgressbar`
- [Core Stock] `TTT_GetRoundTimeLeft`
- [Core Stock] `TTT_GetRoundTimeElapsed`
- [Core Stock] `TTT_IsClientStuck`
- Added `SteamWorks.inc`
- Added `discord.inc`
- Added `smjansson.inc`
- Added `ttt_shop_discount.inc`
- [Core Include] Added enum `Collision_Group_t` to `ttt.inc`
- [Core Include] Added enum `SolidType_t` to `ttt.inc`
- [Core Native] `TTT_GetRoundTimestamp`
- [Core Native] `TTT_GetClientByRagdollID`
- [Core Native] `TTT_UseClientPanorama`
- [Core Native] `TTT_GetLatestVersion(const char[] version, int length)` - get latest version as string
- [Core Native] `TTT_HasClientKnife(int client)` - returns knife index
- [Core Native] `TTT_HasClientTaser(int client)`
- [Core Native] `TTT_RespawnPlayer` - returns taser index
- [Core Native] `TTT_TerminateRound`
- [Core Native] `TTT_DisableRounds`
- [Core Feature] Flashlight is now activeable with a command (disabled by default)
  - CVar `ttt_flashlight_option` - Default: `0` - `How should flashlight be activated? 0 = +lookatweapon, 1 - Command (sm_fl or sm_flashlight)` 
- [Core Feature] Version Check, that print a message to all players with current ttt version if it's up to date or not
 - CVar `ttt_show_url` - Default: `1` - `Show the URL when a player wants to read the rules? Valve removed the MOTD and Popup-function, so that could be useful` 
 - CVar `ttt_version_check` - Default: `1` - `Enable version check?` 
 - CVar `ttt_version_message` - Default: `1` - `This prints a version message to all players on every spawn` 
 - CVar `ttt_send_server_data` - Default: `1` - `Send the IP and Port to csgottt.com, server will be listed on csgottt.com` 
- [Core Feature] Buttons can be now used for traitor features
- [Core Forward] `TTT_OnPlayerRespawn`
- [Core Forward] `TTT_OnBodyChecked` renamed to `TTT_OnBodyCheck`
- [Core Forward] `TTT_OnLatestVersion(const char[] version)` - get latest version as string
- [Core Forward] Added array with round logs to `TTT_OnRoundEnd`
- [Shop Native] `TTT_GetItemDiscount(int client, const char[] shortName)` - returns discount in percent (as int)
- [Shop Feature] Flag for shop admin commands are now configurable
 - CVar `ttt_shop_give_item_flag` - Default: `z` - `Admin flags to give players shop items` 
 - CVar `ttt_shop_set_credits_flag` - Default: `z` - `Admin flags to set players credits` 
 - CVar `ttt_shop_reset_items_flag` - Default: `z` - `Admin flags to reset all items from shop (Reload)` 
 - CVar `ttt_shop_list_items_flag` - Default: `z` - `Admin flags to list all items from shop` 
 - CVar `ttt_shop_commands` - Default: `shop;menu` - `Commands for ttt shop (up to 6 commands)` 
- [Glow Forward] `TTT_OnGlow` Style added
- [Overlay Native] `TTT_DisableRoleOverlays` 
- [GrabberMod] Added following convars:
  - `gbm_block_push_props` - Default: `1` - `Block props with the MoveType MOVETYPE_PUSH (no clip to world, push and crush)?`
  - `gbm_on_grab_sound` - Default: `ui/item_drop.wav` - `Sound when player grab something (blank = disabled)`
  - `gbm_on_grab_sound_volume` - Default: `0.1` - `Volume of the grab sound`
  - `gbm_on_throw_sound` - Default: `weapons/hegrenade/grenade_throw.wav` - `Sound when player throw a prop (blank = disabled)`
  - `gbm_on_throw_sound_volume` - Default: `1.0` - `Volume of the throw sound`
  - `gbm_grab_distance` - Default: `150.0` - `How long should be max the grab distance?`
  - `gbm_allow_throw` - Default: `1` - `Allow throwing of props?`
  - `gbm_throw_force` - Default: `1000.0` - `How strong should the throw of a prop?`
- [Overlay] Time Overlays
  - `ttt_time_overlays_enable` - Default: `0` - `Enable / Disable time overlays? You could show overlays during a active(!) round. 0 - Disable, 1 - Enable`
  - `ttt_time_overlays_time` - Default: `3.0` - `Time in seconds how long the time overlays will be shown.`
- [Ice Knife]
  - `iceknife_gag` - Default: `1` - `Gag client during freeze time?`
  - `iceknife_hide_playerhud` - Default: `1` - `Hide PlayerHUD during freeze`
  - `iceknife_ice_cube` - Default: `1` - `Set player into a ice cube during freeze?`
  - `iceknife_freeze_volume` - Default: `0.7` - `Volume of freeze sound`
  - `iceknife_unfreeze_volume` - Default: `0.7` - `Volume of unfreeze sound`
- [Random Teleporter] Added following cvars:
  - `rt_traitor_ignore_role` - Default: `4` - `Which role should be ignored when traitor use random teleporter? -1 - Disabled ( https://github.com/Bara/TroubleinTerroristTown/wiki/CVAR-Masks )`
  - `rt_innocent_ignore_role` - Default: `-1` - `Which role should be ignored when innocent use random teleporter? -1 - Disabled ( https://github.com/Bara/TroubleinTerroristTown/wiki/CVAR-Masks )`
  - `rt_detective_ignore_role` - Default: `-1` - `Which role should be ignored when detective use random teleporter? -1 - Disabled ( https://github.com/Bara/TroubleinTerroristTown/wiki/CVAR-Masks )`
- [Weapons]
  - `mp5sd_price` - Default: `3000` - `The amount of credits the MP5-SD costs. 0 to disable.`
  - `mp5sd_sort_prio` - Default: `0` - `The sorting priority of the MP5-SD in the shop menu.`
  - `mp5sd_name` - Default: `MP5-SD` - `The name of the MP5-SD in the shop menu.`
- [Revolver] (Thanks to @good_live)
 - Detective item
 - Traitors are with one shot down but Detective will be slayed when he hits a non Traitor
- [Jammer] (Thanks to @good_live for this idea)
 - Detective Item
 - Traitors with active tracer can't see the Detective with Jammer
- [Missiles] (Thanks to @good_live)
 - For all (depends on configs settings)
 - 3 different modes: Normal, Following and Controllable
- [Bullets] (Thanks to @Luckiris)
 - Traitor Items
 - Available bullets: Poison, Ice and Fire
- [Hurtshot] (Thanks to @Luckiris)
 - Traitor items
 - Like Healthshot but with damage and Hurtshot can be dropped
- Some functions will no longer called in non-active round

Changes/Fixes:
---
- [Core Incude] Updated `futuristicgrenades.inc`
- [Core Incude] Updated `camerasanddrones.inc`
- Replaced all tabs with 4 spaces (just the scripting-Folder)
- Few typos
- Fixed error with datapacks (Rename to old player name should be fixed with this)
- Fixed respawn issue when a players slays himself in the last seconds before round starts
- Fixed proberty error in `TTT_SafeRemoveWeapon` (C4 will be removed now correctly)
- `PrintHintText` replaced with `PrintCenterText`
- `IsClientInGame` replaced with `TTT_IsClientValid`
- `TTT_OnBodyChecked` renamed to `TTT_OnBodyCheck`
-  Shop discounts are now configurable per shop item (File: addons/sourcemod/configs/ttt/shop_discounts.ini)
- Warning message when player opens url menu
- Fixed a bug in team selection, since we pushed some players more than just one time into players array
- Fixed discount logic a bit, now smaller and a bit more efficient
- Fixed bug who doesn't give the player a knife on round start
- Fixed shooting bug when player is in deathmatch
- Fixed bug with free dna scanner
- Fixed TTT message tag in the following shop item: stations
- Fixed bug with buyzone (removed with cvar `0`)
- Fixed bug with tactical shield (short name was too long)
- Don't set role in a inactive round
- Remove C4
- Fix voice issue
- Code Cleanup
- Naming of variables, callbacks, ...

Removed:
---
- [Build] SourceMod 1.8 Builds
- Removed webfix include
- Removed all old discount cvars
- Removed discount bool from native TTT_RegisterCustomItem
- Removed discount bool from native TTT_UpdateCustomItem
- Removed unused stocks, functions and so on

Redie / GhostDM (partially added, but not ready to use!):
--- 

- [x] Weapons Menu (configurable)
  - [ ] Save weapons selection
  - [ ] !guns Command
- [x] Hide Ghosts for alive players (and same for alive players and ghosts)
- [x] Disable Drop/Pickup functions for Ghosts
- [x] No sound for alive players from ghosts (and the same for ghosts and alive players)
- [ ] No credits/karma update while ghost deathmatch

### CODE REVIEW

**Comment by Prefix** [comment]
Can u add more commands than !guns? It would conflict with my !guns command (I have it for donators)

**Comment by Bara** [comment]
I could do that, but TTT isn't a small gamemode and Donator is just a plugin with some (maybe OP or Admin) extra Features for $$$.. I'll thinking about this but the chance is (for me) not high.

**Comment by Bara** [comment]
Some previews for panorama Center Text's:
https://steamcommunity.com/sharedfiles/filedetails/?id=1435120370
https://steamcommunity.com/sharedfiles/filedetails/?id=1435120425
https://steamcommunity.com/sharedfiles/filedetails/?id=1435120515

It should work with HintText, but I keep this for only panorama players as "new" feature.

**Comment by Bara** [comment]
[ttt-1.9.zip](https://github.com/Bara/TroubleinTerroristTown/files/2271616/ttt-1.9.zip)
Here's the build package with latest compiled files.
**materials, models and sounds aren't included!**

**Comment by iNilo** [comment]
See #361 for a "nicer" progress bar

**Comment by Bara** [comment]
Ice Knife got an Update.

Added Gag and Hide PlayerHUD during freeze
It's now possible to set the target into a ice cube: https://youtu.be/qWNRZDxn5bU

**Comment by Bara** [comment]
[ttt-dev-1.9.zip](https://github.com/Bara/TroubleinTerroristTown/files/2465652/ttt-dev-1.9.zip)
Here is the build package! ([SourceCode](https://github.com/Bara/TroubleinTerroristTown/tree/0efbbcedbab732440e25ea2b45d10cb07013d125)).

**Pull request merged**
