### PR TITLE
Add Option to use Bumpmines as Innocent

### PR DESCRIPTION
**Pull request by Saueee**
Add Option to use Bumpmines as Innocent

### CODE REVIEW

**Comment by Mrkl21full** [comment]
Well... If you want to do such a thing, you should add usages per role and then register it depending on the usages (0 means disabled, higher then 0 means enabled for specific role).

**Comment by Saueee** [comment]
I couldn't find out why some Items got 2 Vars like this:
HAMMER_D_ITEM_SHORT
HAMMER_T_ITEM_SHORT
But I don't think this is neccessary for this change. (?)

Also I forgot to set default for bumpmine.type to 2 for Traitor only

**Comment by Mrkl21full** [comment]
Because when you buys something it has a "short name" a "forward event" will pass the thing you just bought and in other plugins you can check if this is from t shop, or d shop and do some actions if necessary.

Your change don't have it, you should add it.

**Comment by Saueee** [comment]
Added T/D Versions. Please review :)

**Comment by Mrkl21full** [comment]
Good work, but it can be optimized.

I can't edit it for you (i don't have the perms :D) but I did it for you (just copy&paste it) [PR-466](https://github.com/Mrkl21full/TroubleinTerroristTown/commit/714f77928f74b64e16e94fbd6c665f8e980065fd)

**Comment by Mrkl21full** [comment]
We only need to let @Bara decide whether "bumpmine_type" should be 1 or 2.

**Comment by Bara** [comment]
@Saueee I did't played with bumpmines yet, does make it any damages to (other) players?

**Comment by Saueee** [comment]
They don't do direct damage but fall damage if players walk over it and can't land anywhere.
They open up some maps because you can jump on towers and houses with them.
Should be traitor only in default in my opinion but option for all would be nice.

**Pull request merged**
