### PR TITLE
Remove not packaged

### PR DESCRIPTION
**Pull request by e54385991**
Un used and build not package

DowDownloading *.com/sound/weapons/rpg/rocket1.wav.bz2.
Error downloading *.com/sound/weapons/rpg/rocket1.wav.bz2
Downloading *.com/sound/weapons/rpg/rocket1.wav.
Error downloading *.com/sound/weapons/rpg/rocket1.wav
Downloading *.com/models/weapons/w_models/w_rocket.mdl.bz2.
Error downloading *.com/models/weapons/w_models/w_rocket.mdl.bz2
Downloading *.com/models/weapons/w_models/w_rocket.mdl.
Error downloading *.com/models/weapons/w_models/w_rocket.mdl
Downloading *.com/materials/models/weapons/w_rocketlauncher/w_rocket01.vmt.bz2.
Error downloading *.com/materials/models/weapons/w_rocketlauncher/w_rocket01.vmt.bz2
Downloading *.com/materials/models/weapons/w_rocketlauncher/w_rocket01.vmt.
Error downloading *.com/materials/models/weapons/w_rocketlauncher/w_rocket01.vmt
Downloading *.com/materials/models/weapons/w_rocketlauncher/w_rocket01.vtf.bz2.
Error downloading *.com/materials/models/weapons/w_rocketlauncher/w_rocket01.vtf.bz2
Downloading *.com/materials/models/weapons/w_rocketlauncher/w_rocket01.vtf.

### CODE REVIEW

**Comment by e54385991** [comment]
can also build add these packages.   otherwise the player will got download error.

**Comment by Bara** [comment]
`sound/weapons/rpg/rocket1.wav` will be used.

**Comment by Bara** [comment]
The others one can be removed.

**Comment by Bara** [comment]
@good-live

**Comment by good-live** [comment]
Yeah both sounds will be used (One while the missile is flying, one for the explosion).
Only the inferno missile is used, The other one is from an ancient version. Couldn't rotate it corretly and therefore switched. TBH Downloading also shouldn't be necessary, since these are all default csgo sounds/models. Only preacaching is necessary.

**Pull request merged**
